[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
rustc-hash = "1.1.0"
log = "0.4.20"
smallvec = "1.11.0"
itertools = "0.11.0"
rayon = "1.7.0"

[profile.release]
debug = true
codegen-units = 1
opt-level = 3
lto = "fat"
panic = "abort"

[profile.dev]
opt-level = 0
