[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
rand = "0.8.5"
smallvec = "1.10.0"
arrayvec = "0.7.2"
tinyvec = "1.6.0"
