[package]
name = "quintessence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
rustc-hash = "1.1.0"
log = "0.4.20"
itertools = "0.11.0"
rayon = "1.7.0"
float-ord = "0.3.2"
microbench = "0.5.0"
bytemuck = "1.14.0"
lazy_static = "1.4.0"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
panic = "abort"
incremental = true

[profile.profile]
inherits = "release"
debug = true
strip = false
