[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
rand = "0.8.5"

[profile.release]
debug = false
codegen-units = 1
opt-level = 3
lto = "fat"
panic = "abort"

[profile.dev]
opt-level = 0
